### ISSUE TITLE
Unable to run the action with tags other than `latest`

### ISSUE THREAD

**Issue by minhbsq** [dutterbutter/era-test-node-action#6]
Example: Specifying the `releaseTag: v0.1.0-alpha.15` will lead to this error

<img width="688" alt="image" src="https://github.com/dutterbutter/era-test-node-action/assets/115865260/35650555-b402-4f9a-9cbc-711f0cf69813">

## Reproduce steps
```
      - name: Run Era Test Node Action
        uses: dutterbutter/era-test-node-action@latest
        with:
          mode: 'run'
          showCalls: 'user'
          showStorageLogs: 'read'
          showVmDetails: 'all'
          showGasDetails: 'all'
          resolveHashes: 'true'
          log: 'info'
          logFilePath: 'era_test_node.log'
          target: 'x86_64-unknown-linux-gnu'
          releaseTag: v0.1.0-alpha.15
```
